#!/bin/sh
### BEGIN INIT INFO
# Provides:          overlay_mount
# Required-Start:    mountkernfs
# Required-Stop:     umountroot
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Overlay the root filesystem with read-write folder
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
  start)
    log_daemon_msg "Starting overlay_mount"
    if ! grep "tmpfs /tmp tmpfs" /proc/mounts ; then
        echo "Create and mount tmpfs /tmp"
        mount -t tmpfs -o rw,suid,dev,exec,nouser,async,noatime,mode=0777,size=64M tmpfs /tmp
    else
        echo "Reusing mounted tmpfs /tmp"
    fi
    mkdir -p /tmp/overlay/etc/upper /tmp/overlay/etc/work \
             /tmp/overlay/home/upper /tmp/overlay/home/work \
             /tmp/overlay/var/upper /tmp/overlay/var/work &&
    mount -t overlay overlay -odefaults,noatime,lowerdir=/etc,upperdir=/tmp/overlay/etc/upper,workdir=/tmp/overlay/etc/work /etc &&
    mount -t overlay overlay -odefaults,noatime,lowerdir=/home,upperdir=/tmp/overlay/home/upper,workdir=/tmp/overlay/home/work /home &&
    mount -t overlay overlay -odefaults,noatime,lowerdir=/var,upperdir=/tmp/overlay/var/upper,workdir=/tmp/overlay/var/work /var &&
    mkdir -p /var/lib/systemd &&
    echo "done" &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac

