#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

if [ ! -x /usr/bin/unsquashfs -o ! -x /bin/lsblk -o ! -x /sbin/blkid -o ! -x /bin/date -o ! -x /usr/bin/lzop ]; then
	exit 1
fi

. /usr/share/initramfs-tools/scripts/functions
. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/unsquashfs
copy_exec /bin/lsblk
copy_exec /sbin/blkid
copy_exec /bin/date
copy_exec /usr/bin/lzop
