#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

if [ ! -x /sbin/fsck ]; then
	exit 1
fi

. /usr/share/initramfs-tools/scripts/functions
. /usr/share/initramfs-tools/hook-functions

fsck_types="xfs ext4 ext2 vfat"

copy_exec /sbin/fsck
copy_exec /sbin/logsave

for type in $fsck_types; do
	if prog="$(command -v "fsck.${type}")"; then
		copy_exec "$prog"
	else
		echo "W: /sbin/fsck.${type} doesn't exist, can't install to initramfs" >&2
	fi
done
